import { collection, addDoc, getDocs, serverTimestamp } from 'firebase/firestore';
import { db } from '../firebase.config';
import type { IncidentType } from '../types/schema';
import { demoCameras } from '../data/demoCameras';

// Helper for RNG intervals
const randomInterval = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1) + min);

class SimulationEngine {
  private timer: ReturnType<typeof setTimeout> | null = null;
  private isRunning = false;

  public async start() {
    if (this.isRunning) return;
    this.isRunning = true;
    this.scheduleNextTick();
    console.log("[Simulation] Engine started.");
  }

  public stop() {
    this.isRunning = false;
    if (this.timer) clearTimeout(this.timer);
    this.timer = null;
    console.log("[Simulation] Engine halted.");
  }

  private scheduleNextTick() {
    if (!this.isRunning) return;
    // Ticks between 25 to 50 seconds randomly
    const delay = randomInterval(25000, 50000);
    this.timer = setTimeout(async () => {
      await this.generateIncident();
      this.scheduleNextTick();
    }, delay);
  }

  private async generateIncident() {
    try {
      const { type, confidence } = this.resolveBehavioralModel();
      const { cameraId, floor, zone } = await this.resolveCameraContext();

      const payload = {
        type,
        confidence,
        cameraId,
        floor,
        zone,
        status: 'active',
        timestamp: serverTimestamp(),
        assignedStaff: null,
        notes: "SIMULATED: Autogenerated by CV Pipeline"
      };

      await addDoc(collection(db, 'incidents'), payload);
      console.log(`[Simulation] Dispatched ${type} with ${confidence}% confidence.`);
    } catch (e) {
      console.error("[Simulation] Engine dispatch failed: ", e);
    }
  }

  // Generate generic logic or query live dataset
  private async resolveCameraContext() {
    try {
      const snap = await getDocs(collection(db, 'cameras'));
      if (!snap.empty) {
        const docs = snap.docs;
        const randomCamera = docs[Math.floor(Math.random() * docs.length)].data();
        if (randomCamera.id && randomCamera.floor && randomCamera.zone) {
          return { cameraId: randomCamera.id, floor: randomCamera.floor, zone: randomCamera.zone };
        }
      }
    } catch (e) {
      console.warn("[Simulation] Cameras lookup failed. Falling back to demo inventory.");
    }

    const fallbackCamera = demoCameras[Math.floor(Math.random() * demoCameras.length)];

    return {
      cameraId: fallbackCamera.id,
      floor: fallbackCamera.floor,
      zone: fallbackCamera.zone
    };
  }

  private resolveBehavioralModel(): { type: IncidentType, confidence: number } {
    const roll = Math.random() * 100;
    if (roll < 30) {
      return { type: 'lip_detection', confidence: randomInterval(65, 82) };
    } else if (roll < 60) {
      return { type: 'gait_anomaly', confidence: randomInterval(60, 79) };
    } else {
      return { type: 'dual_match', confidence: randomInterval(85, 97) };
    }
  }

  // Dramatic demonstration injection bypassing RNG queues
  public async forceDispatchWarning() {
    try {
      const { cameraId, floor, zone } = await this.resolveCameraContext();
      
      const explosivePayload = {
        type: 'dual_match',
        confidence: 96,
        cameraId,
        floor,
        zone,
        status: 'active',
        timestamp: serverTimestamp(),
        assignedStaff: null,
        notes: "SIMULATED TRIGGER: High severity alert dispatched."
      };

      await addDoc(collection(db, 'incidents'), explosivePayload);
      console.log(`[Simulation] OVR-RIDE: Dispatched dual_match with 96% confidence.`);
    } catch (e) {
      console.error("[Simulation] Override dispatch failed: ", e);
    }
  }
}

export const cvSimulator = new SimulationEngine();
